# Generated by Django 5.0.2 on 2024-03-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_package_itinerary_packageexclusion_packageimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image_url',
            field=models.ImageField(null=True, upload_to='photos/package/', verbose_name='Package Image'),
        ),
    ]
