# Generated by Django 5.0.2 on 2024-03-19 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_auth_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=255, verbose_name='Destination Name')),
                ('season', models.CharField(max_length=100, verbose_name='Season')),
                ('description', models.TextField(verbose_name='Description')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('image_url', models.ImageField(null=True, upload_to='photos/destination/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255, verbose_name='Hotel Name')),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pricing')),
                ('contact_no', models.CharField(max_length=20, verbose_name='Contact No')),
                ('hotel_type', models.CharField(max_length=100, verbose_name='Hotel Type')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('rooms', models.PositiveIntegerField(verbose_name='Rooms')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Rating')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='users.destination')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/hotel_images/', verbose_name='Image')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Image',
                'verbose_name_plural': 'Hotel Images',
            },
        ),
        migrations.CreateModel(
            name='HotelItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(verbose_name='Day')),
                ('description', models.TextField(verbose_name='Description')),
                ('activity', models.TextField(blank=True, null=True, verbose_name='Activity')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='users.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Itinerary',
                'verbose_name_plural': 'Hotel Itineraries',
            },
        ),
    ]
