# Generated by Django 5.0.2 on 2024-05-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_destination_hotel_hotelimage_hotelitinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_description',
            field=models.CharField(null=True, verbose_name='Hotel description'),
        ),
    ]
