# Generated by Django 5.0.2 on 2024-05-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_hotel_hotel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255, verbose_name='Point')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='users.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Detail',
                'verbose_name_plural': 'Hotel Details',
            },
        ),
    ]
