# Generated by Django 5.0.2 on 2024-05-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_hoteldetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteldetail',
            old_name='point',
            new_name='detail',
        ),
    ]
