# Generated by Django 5.0.2 on 2024-05-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_hotelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.ImageField(null=True, upload_to='photos/hotel/', verbose_name='Hotel Image'),
        ),
    ]
