# Generated by Django 5.0.2 on 2024-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_hotel_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='duration',
        ),
        migrations.AddField(
            model_name='hotel',
            name='destination_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Destination Name'),
        ),
        migrations.AddField(
            model_name='package',
            name='no_of_days',
            field=models.PositiveIntegerField(null=True, verbose_name='Duration in days'),
        ),
        migrations.AddField(
            model_name='package',
            name='no_of_nights',
            field=models.PositiveIntegerField(null=True, verbose_name='Duration in nights'),
        ),
    ]
