# Generated by Django 5.0.2 on 2024-05-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_package_duration_hotel_destination_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='no_of_days',
            new_name='duration',
        ),
    ]
