# Generated by Django 5.0.2 on 2024-05-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_packagebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='booking_number',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
