# Generated by Django 5.0.2 on 2024-05-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Package Name'),
        ),
    ]
