# Generated by Django 5.0.2 on 2024-06-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_package_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
