# Generated by Django 5.0.2 on 2024-06-07 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_hotelreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreview',
            name='rating',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
